# Generated by Django 4.2.2 on 2023-10-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_alter_criminal_ward_alter_police_ward_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='police',
            name='police_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
