# Generated by Django 4.2.2 on 2023-10-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_remove_police_birth_date_police_police_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='police',
            old_name='police_birth_date',
            new_name='birth_date',
        ),
    ]
