# Generated by Django 4.2.2 on 2023-08-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoustip',
            name='stay_in_touch',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='anonymoustip',
            name='upload_evidence',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='anonymoustip',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.anonymoususer'),
        ),
    ]
