# Generated by Django 4.2.2 on 2023-08-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
        ('case', '0003_case_ward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.casecategory'),
        ),
        migrations.AlterField(
            model_name='case',
            name='cyber_case_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.cybercasecategories'),
        ),
        migrations.AlterField(
            model_name='case',
            name='solved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.citizen'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_evidence', to='case.case'),
        ),
    ]
