# Generated by Django 4.2.2 on 2023-08-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_alter_case_approved_alter_case_case_categories_and_more'),
        ('police', '0002_alter_criminal_ward_alter_police_ward_evidence'),
        ('citizen', '0001_initial'),
        ('comment', '0002_auto_20171210_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.case'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='police.police'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.citizen'),
        ),
    ]
