# Generated by Django 4.2.2 on 2023-10-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_remove_police_birth_date_police_police_birth_date'),
        ('citizen', '0001_initial'),
        ('comment', '0003_alter_comment_case_alter_comment_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_comments', to='police.police'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_comments', to='citizen.citizen'),
        ),
    ]
